# Generated by Django 2.0.6 on 2018-07-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=64)),
                ('bus_seats', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_firstname', models.CharField(max_length=64)),
                ('child_lastname', models.CharField(max_length=64)),
                ('child_school', models.CharField(max_length=64)),
                ('pickup_time', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_firstname', models.CharField(max_length=64)),
                ('driver_lastname', models.CharField(max_length=64)),
                ('driver_license', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'others')])),
                ('phone', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('trip_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cornerstone.Bus')),
                ('trip_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cornerstone.Driver')),
                ('trip_kids', models.ManyToManyField(related_name='_trip_trip_kids_+', to='cornerstone.Child')),
                ('unpicked_kids', models.ManyToManyField(related_name='_trip_unpicked_kids_+', to='cornerstone.Child')),
            ],
        ),
    ]
