# Generated by Django 2.0.6 on 2018-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0002_auto_20180709_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_firstname',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
