# Generated by Django 2.0.6 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0003_auto_20180710_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
