# Generated by Django 2.0.6 on 2018-07-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0005_auto_20180717_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='on_trip',
            field=models.BooleanField(default=False),
        ),
    ]
