# Generated by Django 2.0.6 on 2018-08-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0007_auto_20180730_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=64, unique=True)),
                ('pickup_time', models.CharField(blank=True, max_length=32)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='pickup_time',
        ),
        migrations.AlterField(
            model_name='child',
            name='child_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cornerstone.School'),
        ),
    ]
