# Generated by Django 2.0.6 on 2018-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0010_child_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_school',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='absent_kids',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_kids',
            field=models.ManyToManyField(blank=True, to='cornerstone.Child'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_time',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
