# Generated by Django 2.0.6 on 2018-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0011_auto_20180828_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cornerstone.School'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cornerstone.Bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cornerstone.Driver'),
        ),
    ]
