# Generated by Django 2.0.6 on 2018-10-26 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0014_auto_20181026_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
