# Generated by Django 2.0.6 on 2018-10-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0015_auto_20181026_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cornerstone.StaffUser', unique=True),
        ),
    ]
